FROM python:3.11-slim-bookworm

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-torch.txt .
RUN pip install --no-cache-dir -r requirements-torch.txt

COPY src/app/main_torch.py ./main.py

COPY models/production/inventory_monitor.pt ./models/production/inventory_monitor.pt

# Run the API
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]